name: Main {{cookiecutter.plugin_name}} CI

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: {{cookiecutter.plugin_name}}
          path: {{cookiecutter.plugin_name}}/bin/Release/{{cookiecutter.plugin_name}}.dll